# Generated by Django 5.0.2 on 2024-04-01 15:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20190903_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='client',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(max_length=50),
        ),
    ]
