# Generated by Django 5.0.2 on 2024-04-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190907_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='authorprofile',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
